# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: conor t. o'brien
title: Copyediting
email: ctobrien.copyediting@gmail.com
#website: conortobrien.github.io/website

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: conor-o-brien-75b25997
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title:
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Copyeditor specializing in literary fiction and memoir. I enjoy the process of working with a text to ensure the author’s vision comes through clearly and effectively, free from error. Previous projects include  Kin by Miljenko Jergović and Milongas by Edgardo Cozarinksy, both are forthcoming from [Archipelago Books](https://archipelagobooks.org/). To view my resumé, click [here](https://conortobrien.github.io/website/assets/CTO_Resume.pdf).
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
